HOCO Unity SDK: LiveItemBoxData
LiveItemBoxData
Static Public Member Functions
static async UniTask< LiveItemBoxData[]> GetAll ()
static async UniTask< LiveItemBoxData > GetByUId (string UId)
static async UniTask< LiveItemBoxData > GetOrCreateByUId (string uId)
Does a GetOrCreateByAddress>Create>GetOrCreateByAddress call stack to ensure the LiveItemBoxData exists in the Cloud Database, otherwise it will create a new one.
static async UniTask< LiveItemBoxData > Update (LiveItemBoxData modifiedData)
static async UniTask< bool > Delete (LiveItemBoxData liveData)
static async UniTask< bool > Create (ItemBoxData localData)
Properties
ItemBoxData? ItemBoxData = new ItemBoxData() [get, set]
Properties inherited from LiveCloudData
string Id = string.Empty [get, set]
This unique identifier is used to identify the object in the Cloud MongoDB Database. It is automatically generated when the object is created, and is used for Updating, Deleting, and Querying the object.
Member Function Documentation
GetAll()
static async UniTask< LiveItemBoxData[]> GetAll () inline static
References CloudAPI< T >.GetAll().
GetByUId()
static async UniTask< LiveItemBoxData > GetByUId (string UId) inline static
Referenced by LiveItemBoxData.GetOrCreateByUId().
GetOrCreateByUId()
static async UniTask< LiveItemBoxData > GetOrCreateByUId (string uId) inline static
Does a GetOrCreateByAddress>Create>GetOrCreateByAddress call stack to ensure the LiveItemBoxData exists in the Cloud Database, otherwise it will create a new one.
Parameters
UId Uniqe ID to get or create in the Cloud
Returns
The live data in the cloud
References LiveItemBoxData.Create(), LiveItemBoxData.GetByUId(), and LiveItemBoxData.ItemBoxData.
Update()
static async UniTask< LiveItemBoxData > Update (LiveItemBoxData modifiedData) inline static
References LiveCloudData.Id.
Delete()
static async UniTask< bool > Delete (LiveItemBoxData liveData) inline static
References LiveItemBoxData.Delete().
Referenced by LiveItemBoxData.Delete().
Create()
static async UniTask< bool > Create (ItemBoxData localData) inline static
Referenced by LiveItemBoxData.GetOrCreateByUId().
Property Documentation
ItemBoxData
ItemBoxData? ItemBoxData = new ItemBoxData() get set
Referenced by LiveItemBoxData.GetOrCreateByUId().