HOCO Unity SDK: ItemStats
ItemStats
Public Member Functions
ItemStats ()
ItemStats (PrimaryStats primaryStats, SecondaryStats secondaryStats)
float GetCompoundSecondaryStat (string name, string statModifier, float statMultiplier)
This version of GetStat(string) is used to easily calculate stats based on other stats, for example, HealthRegen is calculated from Endurance.
Properties
PrimaryStats PrimaryStats = new PrimaryStats() [get, protected set]
SecondaryStats SecondaryStats = new SecondaryStats() [get, protected set]
float CompoundSecondary_HealthRegen [get]
An example on how calculate HealthRegen from Endurance.
float CompoundSecondary_MaxHealth [get]
An example on how calculate MaxHealth from Endurance.
Constructor & Destructor Documentation
ItemStats() [1/2]
ItemStats () inline
References ItemStats.PrimaryStats, and ItemStats.SecondaryStats.
ItemStats() [2/2]
ItemStats (PrimaryStats primaryStats, SecondaryStats secondaryStats) inline
Member Function Documentation
GetCompoundSecondaryStat()
float GetCompoundSecondaryStat (string name, string statModifier, float statMultiplier) inline
This version of GetStat(string) is used to easily calculate stats based on other stats, for example, HealthRegen is calculated from Endurance.
Parameters
name
statModifier The name of the value to use to modify the stat
statMultiplier The multiplier of that value to add to the result
Returns
Whatever was in the stat, + the modifier value by the other stats
References BaseStats.GetStat().
Property Documentation
PrimaryStats
PrimaryStats PrimaryStats = new PrimaryStats() get protected set
Referenced by ItemStats.ItemStats().
SecondaryStats
SecondaryStats SecondaryStats = new SecondaryStats() get protected set
Referenced by ItemStats.ItemStats().
CompoundSecondary_HealthRegen
float CompoundSecondary_HealthRegen get
An example on how calculate HealthRegen from Endurance.
CompoundSecondary_MaxHealth
float CompoundSecondary_MaxHealth get
An example on how calculate MaxHealth from Endurance.