HocoWeb3: PlayerDataTestCase
PlayerDataTestCase
Public Member Functions
IEnumerator TestPlayerData ()
void ModifyPlayerData (LivePlayerData _data)
Member Function Documentation
ModifyPlayerData()
void ModifyPlayerData (LivePlayerData _data) inline
References PlayerData.Level, and LivePlayerData.PlayerData.
Referenced by PlayerDataTestCase.TestPlayerData().
TestPlayerData()
IEnumerator TestPlayerData ()
References LivePlayerData.Create(), LivePlayerData.Delete(), LivePlayerData.GetFromPlayerAddress(), PlayerDataTestCase.ModifyPlayerData(), and LivePlayerData.Update().