HOCO Unity SDK: BaseStats
BaseStats
Public Member Functions
BaseStats (Dictionary< string, float > stats)
float GetStat (string name)
void SetStat (string name, float value)
Properties
Dictionary< string, float > Stats = new Dictionary<string, float>() [get, protected set]
Constructor & Destructor Documentation
BaseStats()
BaseStats (Dictionary< string, float > stats) inline
References BaseStats.Stats.
Member Function Documentation
GetStat()
float GetStat (string name) inline
References BaseStats.Stats.
Referenced by ItemStats.GetCompoundSecondaryStat().
SetStat()
void SetStat (string name, float value) inline
References BaseStats.Stats.
Property Documentation
Stats
Dictionary<string, float> Stats = new Dictionary<string, float>() get protected set
Referenced by BaseStats.BaseStats(), BaseStats.GetStat(), PrimaryStats.PrimaryStats(), PrimaryStats.PrimaryStats(), SecondaryStats.SecondaryStats(), SecondaryStats.SecondaryStats(), and BaseStats.SetStat().