HocoWeb3: LivePlayerData
LivePlayerData
This is the data class that is used to store the PlayerData in the Cloud Database. Feel free to alter the included PlayerData class, but keep in mind it will revert to stock after you Update the SDK with a new version.
Public Member Functions
LivePlayerData ()
Static Public Member Functions
static async UniTask< LivePlayerData > GetFromPlayerAddress (string walletAddress)
static async UniTask< LivePlayerData > Update (LivePlayerData modifiedData)
static async UniTask< bool > Delete (LivePlayerData dedData)
static async UniTask< bool > Create (PlayerData newPlayerData)
Create new PlayerData which will wrap the PlayerData into a LivePlayerData and store it in the Cloud Database.
Properties
PlayerData? PlayerData = new PlayerData() [get, set]
Properties inherited from LiveCloudData
string Id = string.Empty [get, set]
This unique identifier is used to identify the object in the Cloud MongoDB Database. It is automatically generated when the object is created, and is used for Updating, Deleting, and Querying the object.
Detailed Description
This is the data class that is used to store the PlayerData in the Cloud Database. Feel free to alter the included PlayerData class, but keep in mind it will revert to stock after you Update the SDK with a new version.
Constructor & Destructor Documentation
LivePlayerData()
LivePlayerData () inline
Referenced by LivePlayerData.Update().
Member Function Documentation
Create()
static async UniTask< bool > Create (PlayerData newPlayerData) inline static
Create new PlayerData which will wrap the PlayerData into a LivePlayerData and store it in the Cloud Database.
This is how you would Create(PlayerData) new PlayerData in your Mongo Database.
var success = await Cloud.CloudBase<bool>.Create<PlayerData>(newPlayerData, k_storageKey);
if(success)                                                                    //Data was created and stored in Database, you can now invoke <see cref="GetFromPlayerAddress(string)"/>
  Debug.Log("PlayerData Created!");                           //using the same <see cref="PlayerData.PlayerAddress"/> you just pushed to the Database
else //Creating Failed, No WAN, or bad config
  Debug.Log("PlayerData Failed to Create :(");
YourClass.YourMethod();
Referenced by PlayerDataTestCase.TestPlayerData().
Delete()
static async UniTask< bool > Delete (LivePlayerData dedData) inline static
References LivePlayerData.Delete().
Referenced by LivePlayerData.Delete(), and PlayerDataTestCase.TestPlayerData().
GetFromPlayerAddress()
static async UniTask< LivePlayerData > GetFromPlayerAddress (string walletAddress) inline static
Referenced by PlayerDataTestCase.TestPlayerData().
Update()
static async UniTask< LivePlayerData > Update (LivePlayerData modifiedData) inline static
References LiveCloudData.Id, LivePlayerData.LivePlayerData(), and LivePlayerData.PlayerData.
Referenced by PlayerDataTestCase.TestPlayerData().
Property Documentation
PlayerData
PlayerData? PlayerData = new PlayerData() get set
Referenced by PlayerDataTestCase.ModifyPlayerData(), and LivePlayerData.Update().